[package]
name = "icecube"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.15.0"

# Taken from minimal-winit pixels example
env_logger = "0.10"
error-iter = "0.4"
log = "0.4"
winit = "0.29"
winit_input_helper = "0.15"
image = "0.25.5"
